- name: paly1
  hosts: local
  tasks:
  - name: play1 and task1 
    ansible.builtin.debug:
      msg: "Hello from play1 and task1"

- name: play2
  hosts: local
  tasks:
  - name: play2 from task1
    ansible.builtin.debug:
      mshg: "Hello from play2 from task1"