- name: vars
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Learner is {{ LEARNER }}"
      
