- name: vars
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter course name
    private: false #It is not confidential
  - name: DURATION
    prompt: Please enter duration
    private: false
  - name: LEARNER
    prompt: Please enter learner name
    private: false
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Learner is {{ LEARNER }}"