- name: variables from Inventory
  hosts: local
  connection: local
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Learner is {{ LEARNER }}"