- name: variables from Inventory # It will pick variables from the inventory file
  hosts: node
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Learner is {{ LEARNER }}"